from . import product_product
from . import account_incoterms
from . import product_template
from . import freight_tags
from . import freight_conditions
from . import commodity_req
from . import partner_type
from . import commodity_data_custom_export
from . import commodity_data_custom_import
from . import commodity_data_approval_import
from . import commodity_data_approval_export
from . import document_type
from . import commodity_group
from . import commodity_data
from . import ports_cities
from . import friegt_settings
from . import service_settings
from . import inherit_res_users
from . import res_partner
from . import res_country
from . import purchase_order
