from . import ocean_data
from . import sea_river
from . import res_company
from . import friegt_settings
from . import service_scope
from . import clearance_type
from . import tracking_stage
from . import activity_type
from . import account_incoterms
from . import res_country
from . import res_partner
from . import inherit_res_users
from . import partner_type
from . import product_product
from . import product_template
from . import container_type
from . import container_data
from . import ports_cities
from . import terminal_port
from . import document_type
from . import freight_conditions
from . import freight_tags
from . import freight_airplane
from . import purchase_order
from . import commodity_group
from . import commodity_data
from . import commodity_req
from . import commodity_data_custom_export
from . import commodity_data_custom_import
from . import commodity_data_approval_import
from . import commodity_data_approval_export
