from . import charge_types
from . import ports_cities
from . import friegt_settings
from . import service_settings
from . import freight_configuration
from . import inherit_res_users
from . import res_partner
from . import account_incoterms
from . import res_country
from . import purchase_order